version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: learning-db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env  # Load variables from the .env file
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
